#!/bin/bash

DNSMASQ_CONF="/etc/NetworkManager/dnsmasq.d/docker-dynamic.conf"
DOMAIN_SUFFIX=".test"

generate_entries() {
    echo "# Auto-generated by docker-dnsmasq-sync.sh"
    for cid in $(docker ps -q); do
        name=$(docker inspect -f '{{.Name}}' "$cid" | sed 's|/||')
        ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$cid")
        if [[ -n "$ip" ]]; then
            echo "address=/$name$DOMAIN_SUFFIX/$ip"
        fi
    done
}

update_dnsmasq() {
    generate_entries > "$DNSMASQ_CONF"
    systemctl restart NetworkManager
}

# Initial run
update_dnsmasq

# Watch Docker events
docker events --filter 'event=start' --filter 'event=stop' --filter 'event=die' | while read -r event; do
    update_dnsmasq
done
