#!/usr/bin/env bash
set -e

echo "[+] Starting Docker and docker-sync..."

sudo systemctl start docker || sudo systemctl start docker.service
sudo systemctl start docker-sync.service || true

echo "[+] Started."
