#!/usr/bin/env bash
set -e

echo "[+] Stopping docker-sync and Docker..."

sudo systemctl stop docker-sync.service || true
sudo systemctl stop  docker.socket  || true
sudo systemctl stop docker || true

echo "[+] Stopped."
