#!/bin/bash

HOSTS_FILE="/etc/docker-dnsmasq-hosts"
DOMAIN_SUFFIX=".test"

generate_entries() {
    echo "# Auto-generated by docker-dnsmasq-sync.sh" > "$HOSTS_FILE"
    for cid in $(docker ps -q); do
        name=$(docker inspect -f '{{.Name}}' "$cid" | sed 's|/||')
        ip=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' "$cid")
        if [[ -n "$ip" ]]; then
            echo "$ip $name$DOMAIN_SUFFIX" >> "$HOSTS_FILE"
        fi
    done
    systemctl restart dnsmasq
}

generate_entries

# Watch docker events to keep it in sync
docker events --filter 'event=start' --filter 'event=stop' --filter 'event=die' | while read -r _; do
    generate_entries
done
